name: Java CI with JUnit and GitHub Pages Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compile Java classes
      run: |
        mkdir -p build
        javac -d build -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" src/*.java tests/*.java
        
    - name: Run JUnit Tests
      run: |
        java -cp "build:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore CalculatorTest
        
    - name: Create Documentation
      run: |
        mkdir -p docs
        echo "# Calculator Java Project" > docs/index.md
        echo "## Automated CI/CD with GitHub Actions" >> docs/index.md
        echo "Last successful build: $(date)" >> docs/index.md
        if [ -f docs/index.md.bak ]; then
          cat docs/index.md.bak >> docs/index.md
        fi
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages 