name: Java CI with JUnit and GitHub Pages Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Explicitly declare dependency versions
env:
  JAVA_VERSION: '11'
  UPLOAD_PAGES_VERSION: 'v1'
  DEPLOY_PAGES_VERSION: 'v2'
  CONFIGURE_PAGES_VERSION: 'v3'
  CHECKOUT_VERSION: 'v3'
  SETUP_JAVA_VERSION: 'v3'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compile Java classes
      run: |
        mkdir -p build
        javac -d build -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" src/*.java tests/*.java
        
    - name: Run JUnit Tests
      run: |
        java -cp "build:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore CalculatorTest
    
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Créer une branche gh-pages
        git checkout --orphan gh-pages
        
        # Supprimer tous les fichiers sauf docs/, index.html, et .nojekyll
        git rm -rf --cached .
        git clean -fd
        
        # S'assurer que .nojekyll existe
        touch .nojekyll
        
        # Ajouter les fichiers nécessaires
        git add index.html
        git add docs/
        git add .nojekyll
        
        # Faire un commit
        git commit -m "Deploy to GitHub Pages"
        
        # Pousser vers GitHub
        git push origin gh-pages --force 