name: Java CI with JUnit and GitHub Pages Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compile Java classes
      run: |
        mkdir -p build
        javac -d build -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" src/*.java tests/*.java
        
    - name: Run JUnit Tests
      run: |
        java -cp "build:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore CalculatorTest
    
    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: class-files
        path: build/
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Create site files
      run: |
        # Create a temporary directory for site files
        mkdir -p _site
        
        # Create index.html in the root that links to all documentation pages
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <title>Projet Calculatrice Java</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>
              body {
                font-family: Arial, sans-serif;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                line-height: 1.6;
              }
              h1 {
                color: #2c3e50;
              }
              ul {
                padding-left: 20px;
              }
              a {
                color: #3498db;
                text-decoration: none;
              }
              a:hover {
                text-decoration: underline;
              }
            </style>
          </head>
          <body>
            <h1>Projet Calculatrice Java</h1>
            <p>Bienvenue sur la documentation du projet Calculatrice Java.</p>
            <ul>
              <li><a href="docs/index.html">Accueil</a></li>
              <li><a href="docs/fonctionnalites.html">Fonctionnalités</a></li>
              <li><a href="docs/api.html">Documentation API</a></li>
              <li><a href="docs/tutoriel.html">Tutoriel</a></li>
              <li><a href="docs/about.html">À propos</a></li>
            </ul>
          </body>
        </html>
        EOF
        
        # Copy docs directory to _site
        cp -r docs _site/
        
        # Create .nojekyll file in the root
        touch _site/.nojekyll
        
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '_site'
        
    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/deploy-pages@v2 