name: Java CI/CD with GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Explicitly declare dependency versions
env:
  JAVA_VERSION: '11'
  UPLOAD_PAGES_VERSION: 'v1'
  DEPLOY_PAGES_VERSION: 'v2'
  CONFIGURE_PAGES_VERSION: 'v3'
  CHECKOUT_VERSION: 'v3'
  SETUP_JAVA_VERSION: 'v3'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Compile Java classes
      run: |
        mkdir -p build
        javac -d build -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" src/*.java tests/*.java
        
    - name: Run JUnit Tests
      run: |
        java -cp "build:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore CalculatorTest
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
        clean: true
        
    - name: Copy HTML files
      run: |
        cp index.html docs/
        cp -r .nojekyll docs/ || touch docs/.nojekyll
        
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs
        
    - name: Deploy GitHub Pages site
      id: deployment
      uses: actions/deploy-pages@v2 