name: Java CI with JUnit and GitHub Pages Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Compile Java classes
      run: |
        mkdir -p build
        javac -d build -cp "lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" src/*.java tests/*.java
        
    - name: Run JUnit Tests
      run: |
        java -cp "build:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore CalculatorTest
        
    - name: Create Documentation Assets
      run: |
        mkdir -p docs/assets/images
        
    - name: Create Build Info
      run: |
        echo "Last successful build: $(date)" > docs/build_info.txt
        echo "Commit: ${{ github.sha }}" >> docs/build_info.txt
        echo "Build number: ${{ github.run_number }}" >> docs/build_info.txt
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true 